version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    id: "qryptic"
    binary: qryptic

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.

    # name_template: >-
    #   {{ .ProjectName }}_
    #   {{- title .Os }}_
    #   {{- if eq .Arch "amd64" }}x86_64
    #   {{- else if eq .Arch "386" }}i386
    #   {{- else }}{{ .Arch }}{{ end }}
    #   {{- if .Arm }}v{{ .Arm }}{{ end }}

    name_template: >-
      qryptic_v{{.Version}}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # use zip for windows archives

    # name_template: "qryptic-v{{.Version}}"
    format_overrides:
      - goos: windows
        format: zip

    files:
      - README.md
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  - name: qryptic
    repository:
      owner: leetsecure
      name: homebrew-tap
    description: Qryptic Client to connect to Qryptic gateways
    homepage: https://github.com/leetsecure/qryptic-client-cli
    dependencies:
      - name: go
      - name: wireguard-tools
    install: |
      bin.install "qryptic"
    test: |
      system "#{bin}/qryptic --version"
    license: AGPL-3.0
    directory: Formula

# The generated checksum after your build. No need to touch this unless you know what you are doing.
checksum:
  name_template: "checksums.txt"
